apiVersion: v1
kind: PersistentVolume
metadata:
  name: opt-alertmanager
  labels:
    type: local
spec:
  storageClassName: manual
  hostPath:
    path: "/opt/alertmanager"
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: opt-alertmanager-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opt-alertmanager-claim
spec:
  storageClassName: ""
  volumeName: "opt-alertmanager"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: alertmanager
spec:
  replicas: 1
  selector:
    matchLabels:
      app: alertmanager
  template:
    metadata:
      labels:
        app: alertmanager
    spec:
      volumes:
        - name: opt-alertmanager
          persistentVolumeClaim:
            claimName: opt-alertmanager-claim
      serviceAccountName: prometheus
      containers:
        - name: alertmanager
          image: prom/alertmanager:v0.21.0
          args:
            - --config.file=/alertmanager/alertmanager.yml
            - --web.external-url=https://bigasterisk.com/alertmanager/
            - --web.route-prefix=/
          ports:
          - containerPort: 9093
          volumeMounts:
          - name: opt-alertmanager
            mountPath: /alertmanager
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: "kubernetes.io/hostname"
                operator: In
                values: ["bang"]
---
apiVersion: v1
kind: Service
metadata:
  name: alertmanager
spec:
  ports:
  - port: 80
    targetPort: 9093
  selector:
    app: alertmanager