apiVersion: v1
kind: PersistentVolume
metadata:
  name: opt-prometheus
  labels:
    type: local
spec:
  storageClassName: manual
  hostPath:
    path: "/opt/prometheus"
  capacity:
    storage: 50Gi
  accessModes:
    - ReadWriteOnce
  persistentVolumeReclaimPolicy: Retain
  claimRef:
    namespace: default
    name: opt-prometheus-claim
---
apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: opt-prometheus-claim
spec:
  storageClassName: ""
  volumeName: "opt-prometheus"
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 50Gi
      