apiVersion: skaffold/v2beta5
kind: Config
metadata: { name: prometheus }
deploy:
  kubectl:
    manifests:
      - "roles.yaml"
      - "deploy.yml"
      - "alertmanager.yml"
      - "kube-state-metrics.yml"
      - "volumes.yaml"